CREATE DATABASE DMD;

GRANT SELECT on DMD.* to 'DMD'@'localhost' IDENTIFIED BY 'MUa2UmQearE6sWfHpNj9';

USE DMD;

DROP TABLE VMP;

CREATE TABLE VMP(VPID DECIMAL(18,0),VPIDDT CHAR(10),VPIDPREV DECIMAL(18,0), VTMID DECIMAL(18,0), INVALID DECIMAL(1,0), NM VARCHAR(255),ABBREVNM VARCHAR(60),BASISCD DECIMAL(4,0),NMDT CHAR(10), NM_PREV VARCHAR(255),BASIS_PREVCD DECIMAL(4,0),NMCHANGECD DECIMAL(4,0), COMBPRODCD DECIMAL(4,0), PRES_STATCD DECIMAL(4,0), SUG_F DECIMAL(1,0), PRES_F DECIMAL(1,0), CFC_F DECIMAL(1,0), NON_AVAILCD DECIMAL(4,0), NON_AVAILDT CHAR(10), DF_INDCD DECIMAL(1,0), UDFS DECIMAL(10,3), UDFS_UOMCD DECIMAL(18,0), UNIT_DOSE_UOMCD DECIMAL(18,0), PRIMARY KEY (VPID), FULLTEXT (NM)) ENGINE MyISAM;

LOAD DATA INFILE '/srv/required/f_vmp_VmpType.csv' INTO TABLE VMP FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n';

ALTER TABLE VMP ADD COLUMN ItemCount INT DEFAULT 0;

DROP TABLE AMP;

CREATE TABLE AMP(APID DECIMAL(18,0),INVALID DECIMAL(1,0), VPID DECIMAL(18,0),NM VARCHAR(255),ABBREVNM VARCHAR(60), DESCRIPTION VARCHAR(700),NMDT CHAR(10), NM_PREV VARCHAR(255), SUPPCD DECIMAL(18,0), LIC_AUTHCD DECIMAL(4,0),  LIC_AUTH_PREVCD DECIMAL(4,0), LIC_AUTHCHANGECD DECIMAL(4,0), LIC_AUTHCHANGEDT CHAR(10), COMBPRODCD DECIMAL(4,0), FLAVOURCD DECIMAL(4,0), EMA DECIMAL(1,0), PARALLEL_IMPORT DECIMAL(1,0), AVAIL_RESTRICTCD DECIMAL(4,0), PRIMARY KEY (APID),
FOREIGN KEY (VPID) REFERENCES VMP(VPID), FULLTEXT (NM,DESCRIPTION)) ENGINE MyISAM;

LOAD DATA INFILE '/srv/required/f_amp_AmpType.csv' INTO TABLE AMP FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n';

ALTER TABLE AMP ADD COLUMN ItemCount INT DEFAULT 0;

DROP TABLE Practices;

CREATE TABLE Practices(PracticeCode CHAR(6),Name VARCHAR(50),NationalGrouping CHAR(3),HighLevelHealthGeography CHAR(3),Address1 VARCHAR(35),Address2 VARCHAR(35),Address3 VARCHAR(35),Address4 VARCHAR(35),Address5 VARCHAR(35),Postcode CHAR(8),OpenDate CHAR(8),CloseDate CHAR(8),StatusCode CHAR(1),OrganisationSubTypeCode CHAR(1),Commissioner  CHAR(3),JoinProvider CHAR(8),LeftProvider CHAR(8),Telephone CHAR(12),BLANK1 BIT,BLANK2 BIT,BLANK3 BIT,AmendedRecord CHAR(1),BLANK4 BIT, Provider CHAR(5),PrescribingSetting CHAR(2),BLANK5 BIT, PRIMARY KEY (PracticeCode), FULLTEXT(Name, Address1,Address2,Address3,Address4,Address5,Postcode)) ENGINE MyISAM;

LOAD DATA INFILE '/srv/required/epraccur.csv' INTO TABLE Practices FIELDS TERMINATED BY ',' ENCLOSED BY '"' LINES TERMINATED BY '\r\n';

DROP TABLE Practitioners;

CREATE TABLE Practitioners(PractitionerCode CHAR(8),Name VARCHAR(50),NationalGrouping CHAR(3),HighLevelHealthGeography CHAR(3),Address1 VARCHAR(35),Address2 VARCHAR(35),Address3 VARCHAR(35),Address4 VARCHAR(35),Address5 VARCHAR(35),Postcode CHAR(8),OpenDate CHAR(8),CloseDate CHAR(8),StatusCode CHAR(1),OrganisationSubTypeCode CHAR(1), PracticeCode CHAR(6),JoinPractice CHAR(8),LeftPractice CHAR(8),Telephone CHAR(12),BLANK1 BIT,BLANK2 BIT,BLANK3 BIT,AmendedRecord CHAR(1),BLANK4 BIT, CareOrganisation CHAR(3), BLANK5 BIT, BLANK6 BIT, BLANK7 BIT, PRIMARY KEY (PractitionerCode),
FOREIGN KEY (PracticeCode) REFERENCES Practices(PracticeCode),  FULLTEXT(Name, Address1,Address2,Address3,Address4,Address5,Postcode)) ENGINE MyISAM;

LOAD DATA INFILE '/srv/required/egpcur.csv' INTO TABLE Practitioners FIELDS TERMINATED BY ',' ENCLOSED BY '"' LINES TERMINATED BY '\r\n';

DELETE FROM Practitioners WHERE LeftPractice !='';